name: Doxygen Action for miniargv

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.9.5
      with:
        doxyfile-path: doc/Doxyfile
        working-directory: "." 
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        node-version: "16"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: doc/html
